[project]
name = 'AgriSure'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.AgriSure]
path = 'contracts/AgriSure.clar'
clarity_version = 3
epoch = 3.1
[contracts.RiskAnalytics]
path = 'contracts/RiskAnalytics.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
